# Change these first
owner: RealDigitalExperiences # Your GitHub organization or username, where this repository lives
repo: site-monitor-upptime # The name of this repository

sites:
  - name: Zeebab
    url: https://www.zeebab.com
  - name: Hennies
    url: https://www.therealhennies.co.za
  - name: Yellow Fat media
    url: https://yellowfatmedia.com
  - name: Ohkayi
    url: https://ohkayi.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /site-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Real Digital Experiences
  introTitle: "**Real Digital Experiences** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Real digital estate
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
